#spring:
#  security:
#    oauth2:
#      client:
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8080/auth/realms/demo
#        registration:
#          keycloak:
#            client-id: app-demo
#            client-secret: e3f519b4-0272-4261-9912-8b7453ac4ecd
server:
  port: 8082